using ChallengeApp11._1;

var employee = new Employee("Aleksy", "Dowejko");
employee.AddGrade("Aleks");
employee.AddGrade("13");
employee.AddGrade(8);
employee.AddGrade(5);
employee.AddGrade(6);
employee.AddGrade(14.87);
var statistics = employee.GetStatisticsWithForEach();
Console.WriteLine($"Average: {statistics.Average:N2}");
Console.WriteLine($"Min: {statistics.Min}");
Console.WriteLine($"Max: {statistics.Max}");
Console.WriteLine();
var statistics1 = employee.GetStatisticsWithFor();
Console.WriteLine($"Average: {statistics1.Average:N2}");
Console.WriteLine($"Min: {statistics1.Min}");
Console.WriteLine($"Max: {statistics1.Max}");
Console.WriteLine();
var statistics2 = employee.GetStatisticsWithWhile();
Console.WriteLine($"Average: {statistics2.Average:N2}");
Console.WriteLine($"Min: {statistics2.Min}");
Console.WriteLine($"Max: {statistics2.Max}");
Console.WriteLine();
var statistics3 = employee.GetStatisticsWithDoWhile();
Console.WriteLine($"Average: {statistics3.Average:N2}");
Console.WriteLine($"Min: {statistics3.Min}");
Console.WriteLine($"Max: {statistics3.Max}");
Console.WriteLine();
